name: openbabel_v1
channels:
- conda-forge
- defaults
dependencies:
    - openbabel
    - pip
    - pip:
         - streamlit
         - molvs==0.1.1
         - rdkit-pypi==2022.3.3
         - protobuf~=3.19.0
